services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  paper:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.11"
      MEMORY: "2G"
      ONLINE_MODE: "false"
      ENFORCE_SECURE_PROFILE: "false"
      OPS: |-
        FishiGames
    volumes:
      - ./paper:/data

  velocity:
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      MEMORY: "1G"
      CFG_MOTD: "Sentinel Development Server"
      REPLACE_ENV_VARIABLES: "true"
    volumes:
      - ./velocity:/server
    ports:
      - "25565:25565"
    depends_on:
      - paper